`timescale 1ns / 1ps


//this code was generated by cReComp
module adder(

input [0:0] clk,

input [0:0] rst,
input [3:0] para0,
input [3:0] para1
);

// //copy this instance to top module
//adder adder
//(
//.clk(bus_clk),
// .rst(rst),
// .para0(para0),
// .para1(para1)
// );




endmodule
