`timescale 1ns / 1ps


//this code was generated by cReComp
module kimura(

input [0:0] clk,

output [15:0] x,
output [15:0] y,
output [15:0] z
);

// //copy this instance to top module
//kimura kimura
//(
//.clk(bus_clk),
// .rst(rst),
// .x(x),
// .y(y),
// .z(z)
//);


endmodule
