`timescale 1ns / 1ps


//this code was generated by cReComp
module sub(

input [0:0] clk,


input [0:0] rst,
input [0:0] req,
output [0:0] busy,
output [0:0] finish,

input [7:0] data_in,
output [7:0] data_out
);

// //copy this instance to top module
//sub sub
//(
//.clk(bus_clk),
// .rst(rst),
// .req(req),
// .busy(busy),
// .finish(finish)
// .rst(rst),
// .data_in(data_in),
// .data_out(data_out)
//);
parameter INIT 	= 0, 
		READY 	= 1,
		PROCESS = 2,
		FINISH 	= 3;

reg [3:0] hs_state;


//for handshake control
always @(posedge clk) begin
	if (rst)
		hs_state <= INIT;
	else
		case (hs_state)
			INIT:					hs_state <= READY;
			READY:		if(req)		hs_state <= PROCESS;
			PROCESS:	if(/*flag*/)hs_state <= FINISH;
			FINISH:					hs_state <= READY;
		endcase
end

assign busy = (hs_state == PROCESS);
assign finish = (hs_state == FINISH);

always @(posedge clk) begin
	if (rst) begin
/*user define port*/
	end
	else if (hs_state == PROCESS) begin
/*user define process*/	
	end
	else if (hs_state == FINISH) begin
/*user define finish action*/	
	end
	else begin
/*user define action*/	
	end
end

endmodule
