`timescale 1ns / 1ps


//this code was generated by cReComp
module top(

input [0:0] clk,

input [0:0] rst_8,
input [7:0] din_8,
input [0:0] wr_en_8,
input [0:0] rd_en_8,
output [7:0] dout_8,
output [0:0] full_8,
output [0:0] empty_8);

// //copy this instance to top module
//top top
//(
//.clk(bus_clk),
//     .rst_8(!user_w_write_8_open && !user_r_read_8_open),
//     .din_8(user_w_write_8_data),
//     .wr_en_8(user_w_write_8_wren),
//     .rd_en_8(user_r_read_8_rden),
//     .dout_8(user_r_read_8_data),
//     .full_8(user_w_write_8_full),
//     .empty_8(user_r_read_8_empty)
//);

//for sub_module "sub"
reg [0:0] req_sub;
wire [0:0] busy_sub;
wire [0:0] finish_sub;


//for 8bit FIFO;
reg fifo_ctl_8;

reg [7:0] data_in;
wire [7:0] data_out;


//instance for sub
sub sub
(
.clk(clk),
.rst(rst),
.req(req),
.busy(busy),
.finish(finish),
.data_in(data_in),
.data_out(data_out)
);

// control block for FIFO of 8bit

// processor => fpga
// If you have asserted "fifo_ctl_8" positive, data will be incomming
// fpga => processor
// If you have asserted "fifo_ctl_8" negative, data will go out
assign full_8 = fifo_ctl_8;
assign empty_8 = ~fifo_ctl_8;

// receive data from processor
always @(posedge clk) begin
	if (rst_8) begin
		fifo_ctl_8 <= 0;
/*user defined init*/
		data_in <= 0;
	end
	else if (wr_en_8 /*busy*/) begin
		fifo_ctl_8 <= 1;
/*user defined rcv*/
		data_in <= din_8[7:0];
	end
	else if (rd_en_8 /*finish*/)begin
		fifo_ctl_8 <= 0;
/*user defined */
	end
end

/*user assign*/
assign dout_8[7:0] = data_out;

//Please set sign for your sub module
always @(posedge clk) begin
	if (rst_8) begin
		req_sub <= 0;
	end
	else if (busy_sub  == 0) begin
		req_sub <= 1;
	end
	else begin
		req_sub <= 0;
	end
end


endmodule
